cart/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('add<int:id>',v.add_to_cart,name='addToCart'),
    path('add_trend<int:id>',v.add_to_cart_trend,name='addToCartTrend'),
    path('add_dis<int:id>',v.add_to_cart_dis,name='addToCartDis'),
    path('-list',v.cart_list,name='List'),
    path('delete<int:id>',v.delete_cart,name='delete'),
    path('delTrend<int:id>',v.delete_cart_trend,name='deleteTrend'),
    path('deleteDis<int:id>',v.delete_cart_dis,name='deleteDis'),
]

library_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('acc-',include(('accounts.urls','accounts'),namespace='account')),
    path('book-',include(('books.urls','books'),namespace='book')),
    path('cart-',include(('cart.urls','cart'),namespace='cart')),
    path('ord-',include(('order.urls','order'),namespace='order')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('list',v.get_order_list,name='List'),
    path('delete<int:id>',v.delete_order,name='deleteOrd'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Order(models.Model):
    totalBill=models.IntegerField()
    status=models.CharField(max_length=30,default="In-Process")
    orderDate=models.DateField(auto_now=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

order/views.py
from django.shortcuts import render,redirect
from cart.models import CartDiscount,CartTrend,Cart,User
from accounts.models import UserInfo
from books.models import BookDiscount,BookTrending,BookInfo,Category
from .models import Order
# Create your views here.

def get_order_list(request):
    uidi=request.session.get('uid')
    u=UserInfo.objects.get(id=uidi)
    balance=u.balance
    uid=request.session.get('_auth_user_id')
    cr=Cart.objects.all()
    crt=CartTrend.objects.all()
    crd=CartDiscount.objects.all()
    o=Order.objects.all()
    ord_list=Order.objects.filter(user=uid)
    cl=Category.objects.all()
    bl=BookInfo.objects.all()
    clist=Cart.objects.filter(user=uid)
    clist_trend=CartTrend.objects.filter(user=uid)
    clist_dis=CartDiscount.objects.filter(user=uid)
    cart_value=0
    order_value=0
    for i in cr:
        cart_value = cart_value + 1 
    for i in crt:
        cart_value = cart_value + 1 
    for i in crd:
        cart_value = cart_value + 1 
    for i in o:
        order_value = order_value + 1
    context={'cr':cr,'crt':crt,'crd':crd,'cl':cl,'bl':bl,'clist':clist,'clist_dis':clist_dis,'ord_list':ord_list,
        'clist_trend':clist_trend,'cart_value':cart_value,'order_value':order_value,'balance':balance}
    return render(request,'order_list.html',context)

def delete_order(request,id):
    or_id=Order.objects.get(id=id)
    or_id.delete()
    return redirect('/ord-list')

order/templates/order_list.html
{%extends 'base3.html'%} {%block data%}

<!-- Shopping Cart -->
<form method="POST">
    {%csrf_token%}
    <div class="shopping-cart section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Shopping Summery -->
                    <table class="table shopping-summery">
                        <thead>
                            <tr class="main-hading">
                                <th>ID</th>
                                <th>TOTAL BILL</th>
                                <th>ORDER DATE</th>
                                <th class="text-center">STATUS</th>
                                <th class="text-center">DELETE<i class="ti-trash remove-icon"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for i in ord_list%}
                            <tr>
                                <td class="product-des" data-title="Description">
                                    <p class="product-name"><a href="">{{i.id}}</a></p>
                                </td>
                                <td class="price" data-title="Price"><span>${{i.totalBill}} </span></td>
                                <td class="total-amount" data-title="Total"><span>{{i.orderDate}}</span></td>
                                <td class="total-amount" data-title="Total"><span>{{i.status}}</span></td>
                                <td class="action" data-title="Remove"><a href="{%url 'order:deleteOrd' i.id%}"><i class="ti-trash remove-icon"></i></a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    <!--/ End Shopping Summery -->
                </div>
            </div>
            
        </div>
    </div>
</form>

{%endblock%}