books/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('byId<int:id>',v.sort_by_category,name='sortByID'),
    path('search',v.search_books,name='search'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('add<int:id>',v.add_to_cart,name='addToCart'),
    path('add_trend<int:id>',v.add_to_cart_trend,name='addToCartTrend'),
    path('add_dis<int:id>',v.add_to_cart_dis,name='addToCartDis'),
    path('-list',v.cart_list,name='List'),
    path('delete<int:id>',v.delete_cart,name='delete'),
    path('delTrend<int:id>',v.delete_cart_trend,name='deleteTrend'),
    path('deleteDis<int:id>',v.delete_cart_dis,name='deleteDis'),
]

library_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('acc-',include(('accounts.urls','accounts'),namespace='account')),
    path('book-',include(('books.urls','books'),namespace='book')),
    path('cart-',include(('cart.urls','cart'),namespace='cart')),
    path('ord-',include(('order.urls','order'),namespace='order')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=30)
    description=models.CharField(max_length=50)

    class Meta:
        db_table='category'

    def __str__(s):
        return s.name

class BookInfo(models.Model):
    name=models.CharField(max_length=40)
    author=models.CharField(max_length=40)
    publisher=models.CharField(max_length=50)
    price=models.IntegerField()
    image=models.ImageField(upload_to='images',default='')
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    class Meta:
        db_table='bookinfo'

    def __str__(s):
        return s.name

class BookDiscount(models.Model):
    name=models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    dis_price=models.IntegerField()

    class Meta:
        db_table='bookdiscount'


class BookFavourite(models.Model):
    name=models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    class Meta:
        db_table='bookfavourite'

class BookTrending(models.Model):
    name=models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    class Meta:
        db_table='booktrending'

books/views.py
from django.shortcuts import render,redirect
from .models import Category,BookTrending,BookDiscount,BookFavourite,BookInfo
from cart.models import Cart,CartDiscount,CartTrend,User
from order.models import Order
from accounts.models import UserInfo
# Create your views here.
def sort_by_category(request,id):
    uid=request.session.get('uid')
    u=UserInfo.objects.get(id=uid)
    balance=u.balance
    cr=Cart.objects.all()
    crt=CartTrend.objects.all()
    crd=CartDiscount.objects.all()
    o=Order.objects.all()
    clist=Cart.objects.filter(user=uid)
    clist_trend=CartTrend.objects.filter(user=uid)
    clist_dis=CartDiscount.objects.filter(user=uid)
    cart_value=0
    order_value=0
    for i in cr:
        cart_value = cart_value + 1 
    for i in crt:
        cart_value = cart_value + 1 
    for i in crd:
        cart_value = cart_value + 1 
    for i in o:
        order_value = order_value + 1
    cl=Category.objects.all()
    bl=BookInfo.objects.all()
    bt=BookTrending.objects.all()
    bd=BookDiscount.objects.all()
    
    bal=0
    for i in clist:
        bal = bal + i.book.price * i.quantity
    for i in clist_trend:
        bal = bal + i.book.name.price * i.quantity
    for i in clist_dis:
        bal = bal + i.book.dis_price * i.quantity

    cl=Category.objects.all()
    bl=BookInfo.objects.filter(category=id)
    context={'cl':cl,'bl':bl,'bd':bd,'bt':bt,'cart_value':cart_value,'order_value':order_value,
        'clist':clist,'clist_trend':clist_trend,'clist_dis':clist_dis,'balance':balance,'bal':bal}
    return render(request,'home.html',context)

def book_types(request):
    bt=BookTrending.objects.all()
    bd=BookDiscount.objects.all()
    context={'bd':bd,'bt':bt}
    return render(request,'home.html',context)

def search_books(request):
    uid=request.session.get('uid')
    u=UserInfo.objects.get(id=uid)
    balance=u.balance
    cr=Cart.objects.all()
    crt=CartTrend.objects.all()
    crd=CartDiscount.objects.all()
    o=Order.objects.all()
    clist=Cart.objects.filter(user=uid)
    clist_trend=CartTrend.objects.filter(user=uid)
    clist_dis=CartDiscount.objects.filter(user=uid)
    cart_value=0
    order_value=0
    for i in cr:
        cart_value = cart_value + 1 
    for i in crt:
        cart_value = cart_value + 1 
    for i in crd:
        cart_value = cart_value + 1 
    for i in o:
        order_value = order_value + 1
    cl=Category.objects.all()
    bl=BookInfo.objects.all()
    bt=BookTrending.objects.all()
    bd=BookDiscount.objects.all()
    
    bal=0
    for i in clist:
        bal = bal + i.book.price * i.quantity
    for i in clist_trend:
        bal = bal + i.book.name.price * i.quantity
    for i in clist_dis:
        bal = bal + i.book.dis_price * i.quantity

    cl=Category.objects.all()
    bl=BookInfo.objects.all()
    if request.method=='POST':
        pname=request.POST.get('srch')
        bl=BookInfo.objects.filter(name__contains=pname)
        context={'cl':cl,'bl':bl,'bd':bd,'bt':bt,'cart_value':cart_value,'order_value':order_value,
        'clist':clist,'clist_trend':clist_trend,'clist_dis':clist_dis,'balance':balance,'bal':bal}
        return render(request,'search.html',context)
    else:
        context={'cl':cl,'bl':bl,'bd':bd,'bt':bt,'cart_value':cart_value,'order_value':order_value,
        'clist':clist,'clist_trend':clist_trend,'clist_dis':clist_dis,'balance':balance,'bal':bal}
        return render(request,'search.html',context)

books/templates/search.html
{%extends 'base1.html'%}{%block data%}

<div class="product-area section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h2>All Books</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="product-info">
                    <div class="nav-main">
                        <!-- Tab Nav -->
                        
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            {%for i in cl%}   
                            <li class="nav-item"><a class="nav-link active"  href="{%url 'book:sortByID' i.id%}" role="tab">{{i.name}}</a></li>
                            {%endfor%}  
                        </ul>
                        
                        <!--/ End Tab Nav -->
                    </div>
                    <div class="tab-content" id="myTabContent">
                        <!-- Start Single Tab -->
                        <div class="tab-pane fade show active" id="man" role="tabpanel">
                            <div class="tab-single" id="allbooks">
                                <div class="row">
                                    {%for i in bl%}
                                    <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                                        <div class="single-product">
                                            <div class="product-img">
                                                <a href="product-details.html">
                                                    <img class="default-img" src="{{i.image}}" alt="#">
                                                    <img class="hover-img" src="{{i.image}}" alt="#">
                                                </a>
                                                <div class="button-head">
                                                    <div class="product-action">
                                                        <a data-toggle="modal" data-target="#exampleModal" title="Quick View" href="#"><i class=" ti-eye"></i><span>Quick Shop</span></a>
                                                        <a title="Wishlist" href="#"><i class=" ti-heart "></i><span>Add to Wishlist</span></a>
                                                    </div>
                                                    <div class="product-action-2">
                                                        <a title="Add to cart" href="{%url 'cart:addToCart' i.id%}">Add to cart</a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="product-content">
                                                <h3><a href="product-details.html">{{i.name}}</a></h3>
                                                <h3><a href="#">{{i.author}}</a></h3>
                                                <div class="product-price">
                                                    <span>$ {{i.price}}/-</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {%endfor%}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{%endblock%}