cart/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('add<int:id>',v.add_to_cart,name='addToCart'),
    path('add_trend<int:id>',v.add_to_cart_trend,name='addToCartTrend'),
    path('add_dis<int:id>',v.add_to_cart_dis,name='addToCartDis'),
    path('-list',v.cart_list,name='List'),
    path('delete<int:id>',v.delete_cart,name='delete'),
    path('delTrend<int:id>',v.delete_cart_trend,name='deleteTrend'),
    path('deleteDis<int:id>',v.delete_cart_dis,name='deleteDis'),
]

library_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('acc-',include(('accounts.urls','accounts'),namespace='account')),
    path('book-',include(('books.urls','books'),namespace='book')),
    path('cart-',include(('cart.urls','cart'),namespace='cart')),
    path('ord-',include(('order.urls','order'),namespace='order')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from books.models import BookInfo,BookDiscount,BookTrending

# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    book=models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    class Meta:
        db_table='cart'

class CartDiscount(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    book=models.ForeignKey(BookDiscount,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    class Meta:
        db_table='cart_dis'
    
class CartTrend(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    book=models.ForeignKey(BookTrending,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    class Meta:
        db_table='cart_trend'

cart/views.py
from django.shortcuts import redirect, render
from books.models import BookTrending,BookDiscount,BookInfo,BookFavourite, Category
from order.models import Order
from .models import Cart,CartDiscount,CartTrend,User
from accounts.models import UserInfo
# Create your views here.

def add_to_cart(request,id):
    book=BookInfo.objects.get(id=id)
    uid=request.session.get('_auth_user_id')
    user=User.objects.get(id=uid)
    cr=Cart()
    cr.user=user
    cr.book=book
    #cr.quantity=request.POST.get('quantity')
    cr.save()
    return redirect('/')

def add_to_cart_trend(request,id):
    book=BookTrending.objects.get(id=id)
    uid=request.session.get('_auth_user_id')
    user=User.objects.get(id=uid)
    crt=CartTrend()
    crt.user=user
    crt.book=book
    #crt.quantity=request.POST.get('quantity')
    crt.save()
    return redirect('/')

def add_to_cart_dis(request,id):
    book=BookDiscount.objects.get(id=id)
    uid=request.session.get('_auth_user_id')
    user=User.objects.get(id=uid)
    crd=CartDiscount() 
    crd.user=user
    crd.book=book
    #crd.quantity=request.POST.get('quantity')
    crd.save()
    return redirect('/')

def cart_list(request):
    uid=request.session.get('uid')
    u=UserInfo.objects.get(id=uid)
    balance=u.balance
    uid=request.session.get('_auth_user_id')
    cr=Cart.objects.all()
    crt=CartTrend.objects.all()
    crd=CartDiscount.objects.all()
    o=Order.objects.all()
    cl=Category.objects.all()
    bl=BookInfo.objects.all()
    clist=Cart.objects.filter(user=uid)
    clist_trend=CartTrend.objects.filter(user=uid)
    clist_dis=CartDiscount.objects.filter(user=uid)
    cart_value=0
    order_value=0
    for i in cr:
        cart_value = cart_value + 1 
    for i in crt:
        cart_value = cart_value + 1 
    for i in crd:
        cart_value = cart_value + 1 
    for i in o:
        order_value = order_value + 1
    if request.method=='POST':
        bal=request.POST.get('bal')
        order=Order()
        order.totalBill=bal
        order.user=User.objects.get(id=uid)
        order.save()
        for i in clist:
            i.delete()
        for i in clist_dis:
            i.delete()
        for i in clist_trend:
            i.delete()
        return redirect('/')
    else:
        bal=0
        for i in clist:
            bal = bal + i.book.price * i.quantity
        for i in clist_trend:
            bal = bal + i.book.name.price * i.quantity
        for i in clist_dis:
            bal = bal + i.book.dis_price * i.quantity
        context={'cr':cr,'crt':crt,'crd':crd,'cl':cl,'bl':bl,'clist':clist,'clist_dis':clist_dis,
        'clist_trend':clist_trend,'cart_value':cart_value,'order_value':order_value,'bal':bal,'balance':balance}
        return render(request,'cart_list.html',context)
    
def delete_cart(request,id):
    cr_id=Cart.objects.get(id=id)
    cr_id.delete()
    return redirect('/cart--list')

def delete_cart_trend(request,id):
    crt_id=CartTrend.objects.get(id=id)
    crt_id.delete()
    return redirect('/cart--list')

def delete_cart_dis(request,id):
    crd_id=CartDiscount.objects.get(id=id)
    crd_id.delete()
    return redirect('/cart--list')

cart/templates/cart_list.html
{%extends 'base3.html'%} {%block data%}

<!-- Shopping Cart -->
<form method="POST">
    {%csrf_token%}
    <div class="shopping-cart section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Shopping Summery -->
                    <table class="table shopping-summery">
                        <thead>
                            <tr class="main-hading">
                                <th>PRODUCT</th>
                                <th>NAME</th>
                                <th class="text-center">UNIT PRICE</th>
                                <th class="text-center">QUANTITY</th>
                                <th class="text-center">TOTAL</th> 
                                <th class="text-center"><i class="ti-trash remove-icon"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for i in clist%}
                            <tr>
                                <td class="image" data-title="No"><img src="{{i.book.image}}" alt="#"></td>
                                <td class="product-des" data-title="Description">
                                    <p class="product-name"><a href="">{{i.book}}</a></p>
                                    <p class="product-des">{{i.book.author}}</p>
                                </td>
                                <td class="price" data-title="Price"><span>${{i.book.price}} </span></td>
                                <td class="qty" data-title="Qty"><!-- Input Order -->
                                    <div class="input-group">
                                        <div class="button minus">
                                            <button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
                                                <i class="ti-minus"></i>
                                            </button>
                                        </div>
                                        <input type="text" name="quant[1]" class="input-number"  data-min="1" data-max="100" value="1">
                                        <div class="button plus">
                                            <button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
                                                <i class="ti-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <!--/ End Input Order -->
                                </td>
                                <td class="total-amount" data-title="Total"><span>{{i.book.price}}</span></td>
                                <td class="action" data-title="Remove"><a href="{%url 'cart:delete' i.id%}"><i class="ti-trash remove-icon"></i></a></td>
                            </tr>
                            {%endfor%}
    
                            {%for i in clist_trend%}
                            <tr>
                                <td class="image" data-title="No"><img src="{{i.book.name.image}}" alt="#"></td>
                                <td class="product-des" data-title="Description">
                                    <p class="product-name"><a href="">{{i.book.name}}(Trending)</a></p>
                                    <p class="product-des">{{i.book.name.author}}</p>
                                </td>
                                <td class="price" data-title="Price"><span>${{i.book.name.price}} </span></td>
                                <td class="qty" data-title="Qty"><!-- Input Order -->
                                    <div class="input-group">
                                        <div class="button minus">
                                            <button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
                                                <i class="ti-minus"></i>
                                            </button>
                                        </div>
                                        <input type="text" name="quant[1]" class="input-number"  data-min="1" data-max="100" value="1">
                                        <div class="button plus">
                                            <button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
                                                <i class="ti-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <!--/ End Input Order -->
                                </td>
                                <td class="total-amount" data-title="Total"><span>{{i.book.name.price}}</span></td>
                                <td class="action" data-title="Remove"><a href="{%url 'cart:deleteTrend' i.id%}"><i class="ti-trash remove-icon"></i></a></td>
                            </tr>
                            {%endfor%}
    
                            {%for i in clist_dis%}
                            <tr>
                                <td class="image" data-title="No"><img src="{{i.book.name.image}}" alt="#"></td>
                                <td class="product-des" data-title="Description">
                                    <p class="product-name"><a href="">{{i.book.name}}(On Sale)</a></p>
                                    <p class="product-des">{{i.book.name.author}}</p>
                                </td>
                                <td class="price" data-title="Price"><span>${{i.book.dis_price}} </span></td>
                                <td class="qty" data-title="Qty"><!-- Input Order -->
                                    <div class="input-group">
                                        <div class="button minus">
                                            <button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
                                                <i class="ti-minus"></i>
                                            </button>
                                        </div>
                                        <input type="text" name="quant[1]" class="input-number"  data-min="1" data-max="100" value="1">
                                        <div class="button plus">
                                            <button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="quant[1]">
                                                <i class="ti-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <!--/ End Input Order -->
                                </td>
                                <td class="total-amount" data-title="Total"><span>{{i.book.dis_price}}</span></td>
                                <td class="action" data-title="Remove"><a href="{%url 'cart:deleteDis' i.id%}"><i class="ti-trash remove-icon"></i></a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    <!--/ End Shopping Summery -->
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Total Amount -->
                    <div class="total-amount">
                        <div class="row">
                            <div class="col-lg-8 col-md-5 col-12">
                                <div class="left">
                                    <div class="coupon">
                                        <form action="#" target="_blank">
                                            <input name="Coupon" placeholder="Enter Your Coupon">
                                            <button class="btn">Apply</button>
                                        </form>
                                    </div>
                                    <div class="checkbox">
                                        <label class="checkbox-inline" for="2"><input name="news" id="2" type="checkbox"> Shipping (+10$)</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-7 col-12">
                                <div class="right">
                                    <ul>
                                        <li>Cart Subtotal<span>${{bal}}/-</span></li>
                                        <li>Shipping<span>Free</span></li>
                                        <li>You Save<span>$20.00</span></li>
                                        <li class="last">You Pay<span><input type="number" name="bal" value="{{bal}}"></span></li>
                                    </ul>
                                    <div class="button5">
                                        <button type="submit" class="btn">Checkout</button>
                                        <a href="/" class="btn">Continue shopping</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/ End Total Amount -->
                </div>
            </div>
        </div>
    </div>
</form>

{%endblock%}