accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

urlpatterns = [
    path('reg',v.register,name='register'),
    path('login',v.log_in,name='login'),
    path('logout',v.log_out,name='logout'),
    path('edit',v.edit_user,name='edit'),
]

books/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('byId<int:id>',v.sort_by_category,name='sortByID'),
    path('search',v.search_books,name='search'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('add<int:id>',v.add_to_cart,name='addToCart'),
    path('add_trend<int:id>',v.add_to_cart_trend,name='addToCartTrend'),
    path('add_dis<int:id>',v.add_to_cart_dis,name='addToCartDis'),
    path('-list',v.cart_list,name='List'),
    path('delete<int:id>',v.delete_cart,name='delete'),
    path('delTrend<int:id>',v.delete_cart_trend,name='deleteTrend'),
    path('deleteDis<int:id>',v.delete_cart_dis,name='deleteDis'),
]

library_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('acc-',include(('accounts.urls','accounts'),namespace='account')),
    path('book-',include(('books.urls','books'),namespace='book')),
    path('cart-',include(('cart.urls','cart'),namespace='cart')),
    path('ord-',include(('order.urls','order'),namespace='order')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="zxx">
<head>
    {%load static%}
	<!-- Meta Tag -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name='copyright' content=''>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Title Tag  -->
    <title>E-Library</title>
	<!-- Favicon -->
	<link rel="icon" type="image/png" href="{%static 'images/logo11.png'%}">
	<!-- Web Font -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
	
	<!-- StyleSheet -->
	<link rel="stylesheet" href="{%static 'css/style.css'%}">
	
	<!-- Bootstrap -->
	<link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
	<!-- Magnific Popup -->
    <link rel="stylesheet" href="{%static 'css/magnific-popup.min.css'%}">
	<!-- Font Awesome -->
    <link rel="stylesheet" href="{%static 'css/font-awesome.css'%}">
	<!-- Fancybox -->
	<link rel="stylesheet" href="{%static 'css/jquery.fancybox.min.css'%}">
	<!-- Themify Icons -->
    <link rel="stylesheet" href="{%static 'css/themify-icons.css'%}">
	<!-- Nice Select CSS -->
    <link rel="stylesheet" href="{%static 'css/niceselect.css'%}">
	<!-- Animate CSS -->
    <link rel="stylesheet" href="{%static 'css/animate.css'%}">
	<!-- Flex Slider CSS -->
    <link rel="stylesheet" href="{%static 'css/flex-slider.min.css'%}">
	<!-- Owl Carousel -->
    <link rel="stylesheet" href="{%static 'css/owl-carousel.css'%}">
	<!-- Slicknav -->
    <link rel="stylesheet" href="{%static 'css/slicknav.min.css'%}">
	
	<!-- Eshop StyleSheet -->
	<link rel="stylesheet" href="{%static 'css/reset.css'%}">
	<link rel="stylesheet" href="{%static 'style.css'%}">
    <link rel="stylesheet" href="{%static 'css/responsive.css'%}">

	
	
</head>
<body class="js">
	
	<!-- Preloader -->
	<div class="preloader">
		<div class="preloader-inner">
			<div class="preloader-icon">
				<span></span>
				<span></span>
			</div>
		</div>
	</div>
	<!-- End Preloader -->
	
	<!-- Header -->
	{%include 'header.html'%}
	<!--/ End Header -->
	
	<!-- Slider Area -->
	{%include 'slider.html'%}
	<!-- End Slider Area -->
	
	<!-- Start Product Area -->
    {%block data%}

    {%endblock%}
	<!-- End Product Area -->
	
	


	
	<!-- Start Shop Services Area -->
	<section class="shop-services section home">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-rocket"></i>
						<h4>Free shiping</h4>
						<p>Orders over $100</p>
					</div>
					<!-- End Single Service -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-reload"></i>
						<h4>Free Return</h4>
						<p>Within 30 days returns</p>
					</div>
					<!-- End Single Service -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-lock"></i>
						<h4>Sucure Payment</h4>
						<p>100% secure payment</p>
					</div>
					<!-- End Single Service -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Start Single Service -->
					<div class="single-service">
						<i class="ti-tag"></i>
						<h4>Best Peice</h4>
						<p>Guaranteed price</p>
					</div>
					<!-- End Single Service -->
				</div>
			</div>
		</div>
	</section>
	<!-- End Shop Services Area -->
	
	<!-- Start Shop Newsletter  -->
	<section class="shop-newsletter section">
		<div class="container">
			<div class="inner-top">
				<div class="row">
					<div class="col-lg-8 offset-lg-2 col-12">
						<!-- Start Newsletter Inner -->
						<div class="inner">
							<h4>Newsletter</h4>
							<p> Subscribe to our newsletter and get <span>10%</span> off your first purchase</p>
							<form action="mail/mail.php" method="get" target="_blank" class="newsletter-inner">
								<input name="EMAIL" placeholder="Your email address" required="" type="email">
								<button class="btn">Subscribe</button>
							</form>
						</div>
						<!-- End Newsletter Inner -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Shop Newsletter -->
	
	
	
	<!-- Start Footer Area -->
	{%include 'footer.html'%}
	<!-- /End Footer Area -->
 
	<!-- Jquery -->
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'js/jquery-migrate-3.0.0.js'%}"></script>
	<script src="{%static 'js/jquery-ui.min.js'%}"></script>
	<!-- Popper JS -->
	<script src="{%static 'js/popper.min.js'%}"></script>
	<!-- Bootstrap JS -->
	<script src="{%static 'js/bootstrap.min.js'%}"></script>
	<!-- Slicknav JS -->
	<script src="{%static 'js/slicknav.min.js'%}"></script>
	<!-- Owl Carousel JS -->
	<script src="{%static 'js/owl-carousel.js'%}"></script>
	<!-- Magnific Popup JS -->
	<script src="{%static 'js/magnific-popup.js'%}"></script>
	<!-- Waypoints JS -->
	<script src="{%static 'js/waypoints.min.js'%}"></script>
	<!-- Countdown JS -->
	<script src="{%static 'js/finalcountdown.min.js'%}"></script>
	<!-- Nice Select JS -->
	<script src="{%static 'js/nicesellect.js'%}"></script>
	<!-- Flex Slider JS -->
	<script src="{%static 'js/flex-slider.js'%}"></script>
	<!-- ScrollUp JS -->
	<script src="{%static 'js/scrollup.js'%}"></script>
	<!-- Onepage Nav JS -->
	<script src="{%static 'js/onepage-nav.min.js'%}"></script>
	<!-- Easing JS -->
	<script src="{%static 'js/easing.js'%}"></script>
	<!-- Active JS -->
	<script src="{%static 'js/active.js'%}"></script>
</body>
</html>

templates/header.html
{%load static%}
<header class="header shop">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-12">
                    <!-- Top Left -->
                    <div class="top-left">
                        <ul class="list-main">
                            <li><i class="ti-headphone-alt"></i> +91 9822-801-582</li>
                            <li><i class="ti-email"></i> support@elibrary.com</li>
                        </ul>
                    </div>
                    <!--/ End Top Left -->
                </div>
                <div class="col-lg-8 col-md-12 col-12">
                    <!-- Top Right -->
                    <div class="right-content">
                        <ul class="list-main">
                            {%if user.is_authenticated%}
                            <li><i class="ti-wallet"></i>${{balance}}</li>
                            <li><i class="ti-user"></i>{{user.first_name|upper}}&nbsp;{{user.last_name|upper}}</li>
                            <li><i class="ti-user"></i> <a href="{%url 'account:edit'%}">My Account</a></li>
                            <li><i class="ti-user"></i> <a href="{%url 'account:logout'%}">Logout</a></li>
                            {%else%}
                            <li><i class="ti-power-off"></i><a href="{%url 'account:login'%}">Login</a></li>
                            {%endif%}
                        </ul>
                    </div>
                    <!-- End Top Right -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <div class="middle-inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-12">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="index.html"><img src="{%static 'images/logo11.png'%}" alt="logo"></a>
                    </div>
                    <!--/ End Logo -->
                    <!-- Search Form -->
                    <div class="search-top">
                        <div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
                        <!-- Search Form -->
                        <div class="search-top">
                            <form class="search-form">
                                <input type="text" placeholder="Search here..." name="search">
                                <button value="search" type="submit"><i class="ti-search"></i></button>
                            </form>
                        </div>
                        <!--/ End Search Form -->
                    </div>
                    <!--/ End Search Form -->
                    <div class="mobile-nav"></div>
                </div>
                <div class="col-lg-8 col-md-7 col-12">
                    <div class="search-bar-top">
                        <div class="search-bar">
                            <a href="{%url 'book:search'%}">Search</a>
                            <form method="POST">
                                {%csrf_token%}
                                <input name="srch" placeholder="Search Book Here....." type="search">
                                <button type="submit" class="btnn"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-12">
                    <div class="right-bar">
                        <!-- Search Form -->
                        {%if user.is_authenticated%}
                        <div class="sinlge-bar shopping">
                            <a href="{%url 'cart:List'%}" class="single-icon"><i class="ti-bag"></i> <span class="total-count">{{cart_value}}</span></a>
                            <a href="{%url 'order:List'%}" class="single-icon"><i class="ti-wallet"></i> <span class="total-count">{{order_value}}</span></a>
                            <!-- Shopping Item -->
                
                            <div class="shopping-item">
                                <div class="dropdown-cart-header">
                                    <span>{{cart_value}} Items</span>
                                    <a href="">View Cart</a>
                                </div>
                                <ul class="shopping-list">
                                    {%for i in clist%}
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href=""><img src="{{i.book.image}}" alt="#"></a>
                                        <h4><a href="">{{i.book}}</a></h4>
                                        <p class="quantity">{{i.quantity}} x<span class="amount">${{i.book.price}}/-</span></p>
                                    </li>
                                    {%endfor%}
                                    {%for i in clist_trend%}
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{{i.book.name.image}}" alt="#"></a>
                                        <h4><a href="#">{{i.book.name}}</a></h4>
                                        <p class="quantity">{{i.quantity}} x<span class="amount">${{i.book.name.price}}/-</span></p>
                                    </li>
                                    {%endfor%}
                                    {%for i in clist_dis%}
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{{i.book.name.image}}" alt="#"></a>
                                        <h4><a href="#">{{i.book.name}}</a></h4>
                                        <p class="quantity">{{i.quantity}} x<span class="amount">${{i.book.dis_price}}/-</span></p>
                                    </li>
                                    {%endfor%}
                                </ul>
                                <div class="bottom">
                                    <div class="total">
                                        <span>Total</span>
                                        <span class="total-amount">$ {{bal}} /-</span>
                                    </div>
                                    <a href="{%url 'cart:List'%}" class="btn animate">Checkout</a>
                                </div>
                            </div>
                            <!--/ End Shopping Item -->
                        
                        {%else%}
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                        </div>
                        {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="cat-nav-head">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="all-category">
                            <h3 class="cat-heading"><i class="fa fa-bars" aria-hidden="true"></i>GENRES</h3>
                            <ul class="main-category">
                                {%for i in cl%}
                                <li><a href="{%url 'book:sortByID' i.id%}">{{i.name}} <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </li>
                                {%endfor%}
                                </ul>
                        </div>
                    </div>
                    <div class="col-lg-9 col-12">
                        <div class="menu-area">
                            <!-- Main Menu -->
                            <nav class="navbar navbar-expand-lg">
                                <div class="navbar-collapse">	
                                    <div class="nav-inner">	
                                        <ul class="nav main-menu menu navbar-nav">
                                                <li class=""><a href="/">Home</a></li>	
                                                <li><a href="#allbooks">Books<i class="ti-angle-down"></i></a>
                                                    <ul class="dropdown">
                                                        <li><a href="#allbooks">All Books</a></li>
                                                        <li><a href="#trend">Trending Books</a></li>
                                                        <li><a href="#discount">Books on Discount</a></li>
                                                    </ul>
                                                </li>
                                                {%if user.is_authenticated%}
                                                <li class=""><a href="{%url 'cart:List'%}">My Carts</a></li>	
                                                <li class=""><a href="{%url 'order:List'%}">My Orders</a></li>	
                                                {%else%}
                                                <li><a href="{%url 'account:register'%}">Register</a></li>	
                                                <li><a href="#">Contact Us</a></li>
                                                {%endif%}
                                            </ul>
                                    </div>
                                </div>
                            </nav>
                            <!--/ End Main Menu -->	
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Inner -->
</header>

templates/header1.html
{%load static%}

<header class="header shop">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-12">
                    <!-- Top Left -->
                    <div class="top-left">
                        <ul class="list-main">
                            <li><i class="ti-headphone-alt"></i> +91 9822-801-582</li>
                            <li><i class="ti-email"></i> support@elibrary.com</li>
                        </ul>
                    </div>
                    <!--/ End Top Left -->
                </div>
                <div class="col-lg-8 col-md-12 col-12">
                    <!-- Top Right -->
                    <div class="right-content">
                        <ul class="list-main">
                            {%if user.is_authenticated%}
                            <li><i class="ti-wallet"></i>${{balance}}</li>
                            <li><i class="ti-user"></i>{{user.first_name|upper}}&nbsp;{{user.last_name|upper}}</li>
                            <li><i class="ti-user"></i> <a href="{%url 'account:edit'%}">My Account</a></li>
                            <li><i class="ti-user"></i> <a href="{%url 'account:logout'%}">Logout</a></li>
                            {%else%}
                            <li><i class="ti-power-off"></i><a href="{%url 'account:login'%}">Login</a></li>
                            {%endif%}
                        </ul>
                    </div>
                    <!-- End Top Right -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <div class="middle-inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-12">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="index.html"><img src="{%static 'images/logo11.png'%}" alt="logo"></a>
                    </div>
                    <!--/ End Logo -->
                    <!-- Search Form -->
                    <div class="search-top">
                        <div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
                        <!-- Search Form -->
                        <div class="search-top">
                            <form class="search-form">
                                <input type="text" placeholder="Search here..." name="search">
                                <button value="search" type="submit"><i class="ti-search"></i></button>
                            </form>
                        </div>
                        <!--/ End Search Form -->
                    </div>
                    <!--/ End Search Form -->
                    <div class="mobile-nav"></div>
                </div>
                <div class="col-lg-8 col-md-7 col-12">
                    <div class="search-bar-top">
                        <div class="search-bar">
                            <form method="POST">
                                {%csrf_token%}
                                <input name="srch" placeholder="Search Books Here....." type="search">
                                <button type="submit" class="btnn"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-12">
                    <div class="right-bar">
                        <!-- Search Form -->
                        {%if user.is_authenticated%}
                        <div class="sinlge-bar shopping">
                            <a href="{%url 'cart:List'%}" class="single-icon"><i class="ti-bag"></i> <span class="total-count">{{cart_value}}</span></a>
                            <a href="{%url 'order:List'%}" class="single-icon"><i class="ti-wallet"></i> <span class="total-count">{{order_value}}</span></a>
                            <!-- Shopping Item -->
                            <!-- Shopping Item -->
                
                            <div class="shopping-item">
                                <div class="dropdown-cart-header">
                                    <span>{{cart_value}} Items</span>
                                    <a href="">View Cart</a>
                                </div>
                                <ul class="shopping-list">
                                    {%for i in clist%}
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href=""><img src="{{i.book.image}}" alt="#"></a>
                                        <h4><a href="">{{i.book}}</a></h4>
                                        <p class="quantity">{{i.quantity}} x<span class="amount">${{i.book.price}}/-</span></p>
                                    </li>
                                    {%endfor%}
                                    {%for i in clist_trend%}
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{{i.book.name.image}}" alt="#"></a>
                                        <h4><a href="#">{{i.book.name}}</a></h4>
                                        <p class="quantity">{{i.quantity}} x<span class="amount">${{i.book.name.price}}/-</span></p>
                                    </li>
                                    {%endfor%}
                                    {%for i in clist_dis%}
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{{i.book.name.image}}" alt="#"></a>
                                        <h4><a href="#">{{i.book.name}}</a></h4>
                                        <p class="quantity">{{i.quantity}} x<span class="amount">${{i.book.dis_price}}/-</span></p>
                                    </li>
                                    {%endfor%}
                                </ul>
                                <div class="bottom">
                                    <div class="total">
                                        <span>Total</span>
                                        <span class="total-amount">$ {{bal}} /-</span>
                                    </div>
                                    <a href="{%url 'cart:List'%}" class="btn animate">Checkout</a>
                                </div>
                            </div>
                            <!--/ End Shopping Item -->
                        {%else%}
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                        </div>
                        {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="cat-nav-head">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="all-category">
                            <h3 class="cat-heading"><i class="fa fa-bars" aria-hidden="true"></i>GENRES</h3>
                            <ul class="main-category">
                                {%for i in cl%}
                                <li><a href="{%url 'book:sortByID' i.id%}">{{i.name}} <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </li>
                                {%endfor%}
                                </ul>
                        </div>
                    </div>
                    <div class="col-lg-9 col-12">
                        <div class="menu-area">
                            <!-- Main Menu -->
                            <nav class="navbar navbar-expand-lg">
                                <div class="navbar-collapse">	
                                    <div class="nav-inner">	
                                        <ul class="nav main-menu menu navbar-nav">
                                                <li class=""><a href="/">Home</a></li>	
                                                <li><a href="#allbooks">Books<i class="ti-angle-down"></i></a>
                                                    <ul class="dropdown">
                                                        <li><a href="#allbooks">All Books</a></li>
                                                        <li><a href="#trend">Trending Books</a></li>
                                                        <li><a href="#discount">Books on Discount</a></li>
                                                    </ul>
                                                </li>
                                                <li class=""><a href="{%url 'cart:List'%}">My Carts</a></li>	
                                                <li class=""><a href="{%url 'order:List'%}">My Orders</a></li>
                                                <li><a href="{%url 'account:register'%}">Register</a></li>
                                                <li><a href="#">Contact Us</a></li>
                                            </ul>
                                    </div>
                                </div>
                            </nav>
                            <!--/ End Main Menu -->	
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Inner -->
</header>

templates/slider.html
{%load static%}

<!-- Start Small Banner  -->
<section class="small-banner section">
    <div class="container-fluid">
        <div class="row">
            <!-- Single Banner  -->
            <div class="col-lg-4 col-md-6 col-12">
                <div class="single-banner">
                    <img src="{%static 'images/ban1.png'%}" alt="#">
                    <div class="content">
                        <p>All Books</p>
                        <h3><span style="color: aliceblue;"> Awesome Collections</span></h3>
                        <a href="#"><span style="color: aliceblue;">Shop Now</span></a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
            <!-- Single Banner  -->
            <div class="col-lg-4 col-md-6 col-12">
                <div class="single-banner">
                    <img src="{%static 'images/ban2.png'%}" alt="#">
                    <div class="content">
                        <p>Trending Books</p>
                        <h3><span style="color: aliceblue;"> Best Collections</span></h3>
                        <a href="#"><span style="color: aliceblue;">Shop Now</span></a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
            <!-- Single Banner  -->
            <div class="col-lg-4 col-12">
                <div class="single-banner tab-height">
                    <img src="{%static 'images/ban3.png'%}" alt="#">
                    <div class="content">
                        <p>Books on Sale</p>
                        <h3><span style="color: aliceblue;"> Affordable Prices</span></h3>
                        <a href="#"><span style="color: aliceblue;">Shop Now</span></a>
                    </div>
                </div>
            </div>
            <!-- /End Single Banner  -->
        </div>
    </div>
</section>
<!-- End Small Banner-->